# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-18 17:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analysisportal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=5)),
                ('watchlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysisportal.Watchlist')),
            ],
        ),
        migrations.RemoveField(
            model_name='stock',
            name='watchlist',
        ),
        migrations.AlterField(
            model_name='stock',
            name='ticker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysisportal.Ticker'),
        ),
    ]
