# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-08 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysisportal', '0002_auto_20170618_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='nextEarningsDate',
            field=models.DateField(null=True),
        ),
    ]
