# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-08 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysisportal', '0003_auto_20170708_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='contractName',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
