# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-10 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysisportal', '0008_auto_20170709_1844'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExhangeHoliday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holidayDate', models.DateField()),
                ('holiday', models.CharField(max_length=45)),
                ('openTo', models.TimeField()),
            ],
        ),
    ]
