# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-11 07:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysisportal', '0009_exhangeholiday'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exhangeholiday',
            old_name='holidayDate',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='exhangeholiday',
            old_name='holiday',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='exhangeholiday',
            old_name='openTo',
            new_name='openToTime',
        ),
    ]
