# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-11 18:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysisportal', '0010_auto_20170711_0856'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExhangeHoliday',
            new_name='ExchangeHoliday',
        ),
    ]
