# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-11 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysisportal', '0011_auto_20170711_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangeholiday',
            name='openToTime',
            field=models.TimeField(null=True),
        ),
    ]
