# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysisportal', '0012_auto_20170711_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='enabled',
            field=models.BooleanField(default=False),
        ),
    ]
