# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-05 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysisportal', '0013_watchlist_enabled'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='nextEarningsDate',
            new_name='earningsDateStart',
        ),
        migrations.AddField(
            model_name='stock',
            name='earningsDateEnd',
            field=models.DateField(default=None, null=True),
        ),
    ]
